# Generated by Django 5.0.1 on 2024-01-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashqlar',
            name='youtobe',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
