# Generated by Django 5.0.1 on 2024-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mashqlar_youtobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.PositiveIntegerField(verbose_name='comment count'),
        ),
    ]
